# para fazer os inserts, basta rodar essa lista em [url da pagina]/mercado/initialInsertDb
from .models import *

def inserts():
    mercados = ['Carrefour', 'Extra', 'Dia a Dia', 'Super Veneza', 'Pão de Açúcar']
    unidades = {
        'Unidade': 'un', 'Quilo': 'kg', 'Grama': 'g', 'Pacote': 'pct',
        'Caixa': 'cx', 'Lata': 'lata', 'Litro': 'lt', 'Bandeja': 'bdj', 'Pote': 'pt',
    }
    categorias = [
        'Mercearia', 'Açougue, Aves, Peixaria', 'Frios e Laticínios',
        'Congelados', 'Condimentos e Molhos', 'Doces',
        'Biscoitos e Aperitivos', 'Bebidas', 'Limpeza', 
        'Cuidados Pessoais', 'Padaria', 'Horti-fruti'
    ]
    marcas = [
        'Nossa Casa', 'Bauducco', 'NutriNectar', 'Kicaldo', 'Batavo', 'Chamyto', 'Qualitá',
        'Carrefour', 'Omo', 'Ypê', 'BomBrill', 'MonBijou', 'Oeste', 'Piracanjuba', 'LeiteBom',
        'CompLeite', 'Bono', 'Copacol', 'Sadia', 'Delícia', 'Fort', 'Royal', 'Da Mamãe', 'Tira Lixo',
        'Bom Ar', 'Elite', 'Itambé', 'Duetto', 'Perdigão', 'Veja', 'Mr Musculo', 'Colgate', 'Oral-B',
        'Gillete', 'Intimus', 'Seda', 'L’oreal Elsève', 'Nívea', 'Protex', 'Johnsons', 'Palmolive', 'Dove',
        'Yoki', 'Glade', 'Brilhante', 'Baby Soft', 'Passe Bem', 'Downy', 'Canto de Minas', 'Tirolez',
        'Philadelphia', 'Vigor', 'Danone', 'Qualy', 'Nestlè','Claybom', 'Paulista',
        'Marilan', 'Vitarella', 'Wickbold', 'Pullman', 'Piraquê', 'Garoto', 'Kibon', 'Texas Burguer',
        'BrasFrut', 'Seara', 'Taeq', 'Pato Purific', 'Urbano', 'Guará', 'Super Frango', 'Aurora', 'Hellmann’s',
        'Fleischmann', 'Forno de Minas', 'Rexona', 'Minuano', 'Tio João', 'Tio Jorge', 'Camil', 'Cristal',
        'Sítio', 'Ubon', 'Predilecta', 'Liza', 'Coqueiro', 'Comigo', 'Soya', 'Zero-Cal', 'Export Moloko',
        'Lebre', 'Cisne', 'Pif Paf', 'Vale do Orizona'
    ]

    produtos = [
        'Feijão', 
        'Açúcar',
        'Café 500g',
        'Óleo',
        'Sal',
        'Macarrão',
        'Milho Pipoca',
        'Farinha de Trigo',
        'Farofa',
        'Achocolatado em Pó',
        'Azeite',
        'Vinagre',
        'Adoçante',
        'Cereal',
        'Leite',
        'Fermento',
        'Maizena',
        'Iogurte',
        'Manteiga',
        'Margarina',
        'Queijo Minas',
        'Queijo Mussarela',
        'Presunto',
        'Yakult',
        'Sorvete',
        'Batata Palito',
        'Ervilha',
        'Polpa Fruta',
        'Leite Condensado',
        'Creme de Leite',
        'Pêssego em Calda',
        'Gelatina em Pó',
        'Chantilly',
        'Ketchup',
        'Mostarda',
        'Maionese',
        'Barbecue',
        'Orégano',
        'Noz Moscada',
        'Bicarbonato',
        'Pimenta do Reino',
        'Batata Palha',
        'Biscoito Água e Sal',
        'Biscoito Recheado',
        'Torrada',
        'Pão de Fôrma',
        'Bisnaguinha',
        'Biscoito Wafer',
        'Filé de Peito de Frango',
        'Filé de Tilápia',
        'Amaciante ',
        'Desinfetante',
        'Limpador Multiuso',
        'Detergente',
        'Desodorizador de Ambiente',
        'Esponja',
        'Esponja de Aço',
        'Sabão em Pó',
        'Sabão em Barra',
        'Saco de Lixo',
        'Álcool',
        'Aparelho de Barbear',
        'Desodorante',
        'Absorvente',
        'Sabonete',
        'Shampoo',
        'Condicionador ',
        'Cotonete',
        'Band-aid', 
        'Sabonete Líquido',
        'Fio Dental',
        'Creme Dental',
        'Papel Higiênico',
        'Filtro de Papel',
        'Ovos',
        'Papel Toalha',
        'Farinha de Rosca',
        'Massa de Tapioca',
        'Flocão de Milho', 
        'Água de Côco', 
        'Bebida Láctea',
        'Suco ',
        'Fermento em Pó',
        'Fermento de Pão',
        'Papel Alumínio', 
        'Saco para Congelar',
        'Copa Lombo',
        'Salsicha',
        'Calabresa',
        'Palmito',
        'Pernil',
        'Linguiça Toscana',
        'Alface',
        'Couve',
        'Cheiro Verde',
        'Maçã',
        'Banana', 
        'Limão',
        'Batata',
        'Cenoura',
        'Abóbora', 
        'Brócolis',
        'Chuchu',
        'Pimentão Verde',
        'Alho',
        'Cebola',
        'Bolinho Bauducco',
        'Hamburguer',
        'Molho de Tomate',
        'Uva',
        'Massa para Pastel',
        'Melancia'
    ]

    unidades_id = [
2,
2,
4,
7,
2,
4,
4,
2,
4,
4,
1,
1,
1,
5,
7,
1,
5,
8,
9,
9,
1,
3,
3,
4,
7,
2,
4,
1,
6,
6,
6,
1,
5,
1,
1,
1,
1,
1,
1,
1,
1,
4,
4,
4,
4,
4,
4, 
4,
2,
4,
7,
7,
7,
1,
1,
4,
4,
5,
4,
1,
7,
4,
1,
4,
1,
1,
1,
5,
5,
7,
1,
1,
4,
5,
4,
4,
4,
4,
4,
1,
1,
1,
3,
3,
1,
1,
2,
2,
2,
1,
2,
2,
1,
1,
1,
2,
2,
2,
2,
2,
2,
1,
2,
2,
2,
2,
1,
5,
1,
2,
 1,
2
    ]

    categorias_id = [
    1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
1,
3,
3,
3,
3,
3,
3,
3,
4,
4,
4,
4,
6,
6,
6,
6,
6,
5,
5,
5,
5,
5,
5,
5,
5,
7,
7,
7,
7,
11,
11,
7,
4,
4,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
9,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
10,
1,
1,
9,
1,
1,
1,
8,
8,
8,
1,
1,
1,
1,
2,
2,
2,
1,
2,
2,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
12,
6,
4,
1,
12,
3,
12
]

    for m in mercados:
        print(f'Mercado: {m}')
        mercado = Mercado(nome = m)
        mercado.save()

    for k, v in unidades.items():
        print(f'Unidade: {k} -> {v}')
        un = Unidade(
            nome = k,
            sigla = v
        )
        un.save()
    
    for c in categorias:
        print(f'Categorias: {c}')
        categoria = Categoria(nome = c)
        categoria.save()
    
    for m in marcas:
        print(f'Marca: {m}')
        marca = Marca(nome = m)
        marca.save()

    for i in range(0, len(produtos)):
        print(f'PRODS: {produtos[i]} | UNIS: {unidades_id[i]} | CATS: {categorias_id[i]}')
        produto = Produto(nome=produtos[i], unidade=Unidade.objects.get(id=unidades_id[i]), categoria=Categoria.objects.get(id=categorias_id[i]))
        produto.save()

    


