# Generated by Django 4.1.3 on 2022-11-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtolista',
            name='mercado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='mercado.mercado'),
        ),
        migrations.AlterField(
            model_name='produtolista',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
