# Generated by Django 4.1.3 on 2022-11-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_alter_produtolista_mercado_alter_produtolista_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtolista',
            name='produto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mercado.produto'),
        ),
    ]
